### ISSUE TITLE
sum_even_fibonacci.cc bug report

### ISSUE THREAD

**Issue by kpomroy** [DavorVuko99/VERSO-Activity#28]
Expected Behavior: This program should sum all even integers between 0 and 4000000.

Actual Behavior: Bugs cause this program to count an inaccurate sum because of the starting value of the sum variable and incorrect checking of whether an integer is even.

Operating System: MacOS
Browser: Safari
Any other relevant information
Possible Solution: Set the sum starting variable equal to 0 instead of 69 on line 8.
Change line 13 to         if (b % 2 == 0) {

Priority: This is a high priority bug because the program does not produce an accurate result.

Reproducibility: This bug can be reproduced easily

Impact: High impact

**Comment by abbyvece** [comment]
fixed the two bugs
