### ISSUE TITLE
even_odd_site.py Bug Report

### ISSUE THREAD

**Issue by jlasewic** [DavorVuko99/VERSO-Activity#29]
Using a Mac, viewed the file even_odd_site.py at 10:55am. The error that I found consisted of a logical error. The program is supposed to sort the numbers 1-50 into odd and even numbers. Instead of taking (i % 2 == 0), it divides i by 2. This creates a table in the html file with all values being store as odd instead of even.

**Comment by abbyvece** [comment]
fixed
